---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web-app
spec:
  replicas: 5
  selector:
    matchLabels:
      name: go-web-app
  template:
    metadata:
      labels:
        name: go-web-app
    spec:
      containers:
      - name: application
        image: kbmuessig/calculationservice:latest
        imagePullPolicy: Always # change to pull after testing
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: go-web-service
spec:
  ports:
  - name: http
    port: 80
    targetPort: 3000
  selector:
    name: go-web-app