---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: calc-service
spec:
  replicas: 1
  selector:
    matchLabels:
      name: calc-service
  template:
    metadata:
      labels:
        name: calc-service
    spec:
      containers:
      - name: application
        image: docker.pkg.github.com/sap-samples/teched2020-developer-keynote/calculationservice:latest
        imagePullPolicy: Always # change to pull after testing
        ports:
          - containerPort: 3000
        resources:
          limits:
            memory: 1000Mi
          requests:
            memory: 32Mi          
      imagePullSecrets:
      - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: calc-service
spec:
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  selector:
    name: calc-service

---
apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: calc-service
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  service:
    name: calc-service
    port: 3000
    host: calc-service
  rules:
    - path: /.*
      methods: ["GET","POST","PUT","DELETE","PATCH","HEAD"]
      accessStrategies:
        - handler: noop
          config: {}    